version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules # the docker will take the node modules you have in you repository to avoid duplicates.
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    env_file:
      ./.env
    volumes:
      - ./postgre:/var/lib/postgresql/data
volumes:
  postgres: