version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - APOLLO_INTROSPECTION=true
      - APOLLO_PLAYGROUND=true
    env_file:
      - ./.env
    networks:
      - postgres
    volumes:
      - ./app:/app/app
      - ./node_modules:/app/node_modules # the docker will take the node modules you have in you repository to avoid duplicates.
    depends_on:
      - postgres
      - pgadmin

  postgres:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - ./postgre:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - postgres
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  api:
  postgres:
  pgadmin: