version: "3"

services:
  postgres:
    image: kartoza/postgis
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - ./postgre:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - app-network

#  nginx:
#    container_name: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    networks:
#      - app-network
#    depends_on:
#      - api

networks:
  app-network:
    driver: bridge

volumes:
  api:
  postgres:
  pgadmin: