version: "3"

services:
  api:
    environment:
      - NODE_ENV=development

  nginx:
    build:
      context: nginx/prod/
      dockerfile: Dockerfile
    volumes:
      - ./nginx-letsencrypt:/etc/letsencrypt

networks:
  postgres:
    driver: bridge

volumes:
  api:
  postgres: