import UserModel from "../../database/models/user.model";
import { generateAuthlink } from "../../auth";
import jwt from "jsonwebtoken";
import { AuthenticationError, UserInputError } from "apollo-server";
import { ApolloError } from "apollo-server-errors";
import { combineResolvers } from "graphql-resolvers";
import { isAuthenticated } from "./authorization";
import ProductModel from "../../database/models/product.model";
import { uploadToS3 } from "../../uploadS3";

const createToken = async (user: UserModel, secret: string) => {
  const payload: Partial<UserModel> = user.toJSON();
  delete payload.password;
  return jwt.sign(payload, secret);
};
declare interface Context {
  user: UserModel;
}

export default {
  Query: {
    getUser: async (_: any, __: any, { user }: { user: UserModel }) => {
      if (!user) {
        return null;
      }
      // TODO : Analytics
      return user;
    }
  },
  Mutation: {
    login: async (
      _: any,
      { email, password }: { email: string; password: string },
      { secret }: { secret: string }
    ) => {
      const user = await UserModel.findByLogin(email);
      if (!user) {
        throw new UserInputError("No user found with this login credentials.");
      }
      const isValid = await UserModel.comparePasswords(password, user.password);

      if (!isValid) {
        throw new AuthenticationError("Invalid password.");
      }
      return { token: createToken(user, secret), userId: user.id };
    },
    register: async (
      _: any,
      {
        email,
        ...userInformations
      }: {
        email: string;
        firstName: string;
        lastName: string;
        password: string;
        phone: string;
      },
      { secret }: { secret: string }
    ) => {
      const emailAlreadyTaken = await UserModel.findOne({
        where: { email }
      });
      if (emailAlreadyTaken) {
        throw new ApolloError(
          "Il semblerais qu'il existe déjà un utilisateur avec cet email.",
          "403"
        );
      }
      const user = await UserModel.create({ ...userInformations, email });

      // TODO : send the generated url to the user via email.
      // this is the link generated by jwt to validate the user. Give it to the user by email to validate his account.
      const validationLink = generateAuthlink("check-email", {
        id: user.id
      });
      console.log(validationLink);
      // TODO : here handle the identification of the user for the analytics.
      return {
        token: createToken(user, secret),
        userId: user.id,
        message: `Un email de confirmation a été envoyé a cette adresse email : ${user.email}, clique sur le lien dans le mail afin valider ton compte !`
      };
    },
    updateUser: combineResolvers(
      isAuthenticated,
      async (
        _: any,
        args: {
          email?: string;
          lastName?: string;
          firstName?: string;
          phone?: string;
          password?: string;
        },
        { user }: Context
      ): Promise<UserModel> => {
        const currentUser = await UserModel.findByPk(user.id);
        if (!currentUser) {
          throw new ApolloError("User not found", "404");
        }
        const toUpdate =
          args.email && args.email != currentUser.email
            ? { ...args, validated: false }
            : { ...args };
        const userResult: [number, UserModel[]] = await UserModel.update(
          toUpdate,
          {
            where: { id: user.id },
            returning: true
          }
        );
        if (userResult[0] === 0)
          throw new ApolloError("Could not update this user", "400");
        return userResult[1][0];
      }
    ),
    updateUserAvatar: combineResolvers(
      isAuthenticated,
      async (
        _: any,
        avatar: {
          stream: Body;
          filename: string;
          mimetype: string;
          encoding: string;
        },
        { user }: Context
      ): Promise<UserModel | null> => {
        //TODO: Delete unused user avatar
        //TODO: Compress with aws lambda
        const { stream, filename } = await avatar.avatar;
        const { name } = await uploadToS3(filename, stream);
        const update = await UserModel.update(
          {
            avatar: name
          },
          { where: { id: user.id } }
        );
        return await UserModel.findByPk(user.id);
      }
    )
  }
};
