name: CI
# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches: [ feat/** ]
  pull_request:
    branches: [ dev ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [ 12.x ]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - name: npm install & build
        run: |
          npm install
          npm run start
